'use client'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../styles/globals.css'
import { AuthContextProvider } from '../context/AuthContext'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
        {children}
        </AuthContextProvider>     
        </body>
    </html>
  )
}

